### ISSUE TITLE
Authentication failure when using in GitHub Action on Linux agent

### ISSUE THREAD

**Issue by flcdrg** [Dejulia489/AzurePipelinesPS#21]
I'm using this module as a step in a GitHub Action workflow.

```yaml
      - name: Queue build
        env:
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        shell: pwsh
        run: |
          Install-Module AzurePipelinesPS -Repository PSGallery -Force
          Import-Module AzurePipelinesPS

          $secureToken = ConvertTo-SecureString -String $env:AZURE_DEVOPS_TOKEN -AsPlainText

          Get-APBuildDefinition -Project MyProject -Collection MyCollection -PersonalAccessToken $secureToken -Instance 'https://dev.azure.com/' -ApiVersion '6.0' -DefinitionID 1 -Verbose
```

If the job that this step runs in has `runs-on: ubuntu-latest`, then the `Get-APBuildDefinition` fails (returns the standard html text saying you need to log in).

If I set `runs-on: windows-latest` then the call succeeds.

Not sure why a Linux runner would cause it to fail
